version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  test:
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout
      - run: yarn
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:12.16.3
    steps:
      - run: print "hello $HEROKU_APP_NAME"
      - heroku/deploy-via-git

workflows:
  version: 2.1
  "heroku deploy":
    jobs:
      - test
      - approval:
          type: approval
          # requires:
          #   - test
          # filters:
          #   branches:
          #     only: master
      - deploy:
          requires:
            - approval
        # filters:
        #   branches:
        #     only: master
