version: 2.1

orbs:
  heroku: circleci/heroku@1.2.5

jobs:
  test-and-build:
    docker:
      - image: circleci/node:16.9.1
    steps:
      - checkout
      - run: yarn
      - run: yarn test
      - run: yarn build

workflows:
  staging:
    jobs:
      - test-and-build
      - approval:
          type: approval
          requires:
            - test-and-build
          filters:
            branches:
              only: master
      - heroku/deploy-via-git:
          requires:
            - approval
