version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  test:
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout
      - run: yarn
      - run: yarn test

workflows:
  staging:
    jobs:
      - test
      - approval:
          type: approval
          # requires:
          #   - test
          # filters:
          #   branches:
          #     only: master
      - heroku/deploy-via-git:
          requires:
            - approval
          # filters:
          #   branches:
          #     only: master
